Neos:
  Neos:
    fusion:
      autoInclude:
        CodeQ.Taggr: true
    userInterface:
      translation:
        autoInclude:
          'CodeQ.Taggr': ['NodeTypes/*']
CodeQ:
  Taggr:
    notice:
      enable: true
